
from pathlib import Path
import json, html
from datetime import datetime

ROOT = Path(__file__).resolve().parent
cfg = json.loads((ROOT/"config.json").read_text(encoding="utf-8"))
data = json.loads((ROOT/"data/latest.json").read_text(encoding="utf-8"))
BASE = cfg["site"].get("base_path","").rstrip("/")

def e(x): return html.escape(str(x or ""))

def card(item):
    return f"""
    <article class="card">
      <div class="meta"><span>{e(item.get('source'))}</span><span>{e(item.get('badge'))}</span></div>
      <h3><a href="{e(item.get('url'))}" target="_blank" rel="noopener noreferrer">{e(item.get('title'))}</a></h3>
      <p>{e(item.get('summary'))}</p>
      {f'<div class="why"><b>Why it matters:</b> {e(item.get("why_it_matters"))}</div>' if item.get("why_it_matters") else ''}
      {f'<div class="care"><b>Why you care:</b> {e(item.get("why_you_care"))}</div>' if item.get("why_you_care") else ''}
    </article>"""

archive_dir = ROOT/"archive"
archive_links = []
for p in sorted(archive_dir.glob("*.html"), reverse=True)[:30]:
    archive_links.append(f'<a href="{BASE}/archive/{e(p.name)}">{e(p.stem)}</a>')

section_html = []
for s in cfg["sections"]:
    items = data["sections"].get(s["id"], [])
    if not items and s["id"] not in ("top","for_you"):
        continue
    body = "".join(card(i) for i in items) or '<p class="muted">No high-signal items today.</p>'
    section_html.append(f'<section id="{e(s["id"])}"><h2>{e(s["title"])}</h2><div class="grid">{body}</div></section>')

signal = ""
if data.get("signal"):
    signal = f'<section class="signal"><h2>💡 The Signal</h2><p>{e(data["signal"])}</p></section>'

doc = f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(cfg["site"]["title"])} — {e(data["date"])}</title>
<style>
:root{{--bg:#f6f3ea;--paper:#fffdf8;--ink:#1f2023;--muted:#74706a;--line:#ddd7ca;}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 ui-serif,Georgia,serif}}
.wrap{{max-width:1080px;margin:auto;padding:36px 20px 80px}}
header{{padding-bottom:24px;border-bottom:2px solid var(--ink)}}
h1{{font-size:clamp(38px,7vw,72px);letter-spacing:-.05em;margin:0}} .sub,.muted{{color:var(--muted)}}
nav,.archive{{display:flex;flex-wrap:wrap;gap:12px;margin-top:16px}} a{{color:inherit}}
nav a,.archive a{{text-decoration:none;border-bottom:1px solid var(--line)}}
section{{margin-top:40px}} h2{{font-size:27px;border-bottom:1px solid var(--line);padding-bottom:8px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:14px}}
.card,.signal{{background:var(--paper);border:1px solid var(--line);border-radius:14px;padding:18px}}
.card h3{{margin:5px 0 8px;line-height:1.3}} .card h3 a{{text-decoration:none}} .card h3 a:hover{{text-decoration:underline}}
.meta{{display:flex;justify-content:space-between;gap:10px;font-size:13px;color:var(--muted)}}
.why,.care{{margin-top:10px;padding:10px 12px;border-radius:8px;background:#f0ece1;font-size:14px}}
footer{{margin-top:50px;color:var(--muted);font-size:13px}}
</style>
</head>
<body><main class="wrap">
<header>
<h1>{e(cfg["site"]["title"])}</h1>
<div class="sub">{e(cfg["site"]["subtitle"])} · {e(data["date"])}</div>
<nav>{''.join(f'<a href="#{e(s["id"])}">{e(s["title"])}</a>' for s in cfg["sections"])}</nav>
<div class="archive"><b>Archive:</b>{''.join(archive_links) if archive_links else '<span class="muted">first issue</span>'}</div>
</header>
{signal}
{''.join(section_html)}
<footer>Generated by Hermes · {e(data.get("generated_at"))}</footer>
</main></body></html>"""

(ROOT/"index.html").write_text(doc, encoding="utf-8")
(ROOT/"archive"/f'{data["date"]}.html').write_text(doc, encoding="utf-8")
(ROOT/"data/archive"/f'{data["date"]}.json').write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Rendered {data['date']}")
